image: mcr.microsoft.com/playwright:v1.48.0-jammy

definitions:
  steps:
    - step: &run-playwright-tests
        name: Run Playwright Tests
        max-time: 60
        script:
          - npm ci
          - npx playwright test --config=playwright.service.config.js --workers=4
        artifacts:
          - playwright-report/**

pipelines:
  branches:
    main:
      - step: *run-playwright-tests
    master:
      - step: *run-playwright-tests
  pull-requests:
    '**':
      - step: *run-playwright-tests
